package com.ark.arkpad.preferences

const val DEFAULT_AUTO_CLUTCH = false

val DEFAULT_BRAKE_EASING = EasingType.FAST_OUT_SLOW_IN
const val DEFAULT_BRAKE_SUSTAIN_MS = 100
const val DEFAULT_BRAKE_RELEASE_MS = 500

val DEFAULT_THROTTLE_EASING = EasingType.LINEAR
const val DEFAULT_THROTTLE_SUSTAIN_MS = 80
const val DEFAULT_THROTTLE_RELEASE_MS = 400

val DEFAULT_SHIFT_UP_KEYCODE = KeyCode.EAST
val DEFAULT_SHIFT_DOWN_KEYCODE = KeyCode.NORTH
val DEFAULT_CLUTCH_KEYCODE = KeyCode.TL
val DEFAULT_HANDBRAKE_KEYCODE = KeyCode.SOUTH